Add timeout to query
GadgetReactor/pyHS100 pull request #19
Opened 2016-12-17 05:09 UTC by trainman419

Add a timeout to the socket; should help home-assistant and others avoid hanging during startup.

I haven't tried this in home-assistant, but I've tried it in the example CLI and I get:

```
$ python3 examples/cli.py 192.168.1.105
DEBUG:pyHS100.protocol:> (31) {"system": {"get_sysinfo": {}}}
Traceback (most recent call last):
  File "/home/hendrix/home/pyHS100/pyHS100/pyHS100.py", line 103, in _query_helper
    request={target: {cmd: arg}}
  File "/home/hendrix/home/pyHS100/pyHS100/protocol.py", line 51, in query
    chunk = sock.recv(4096)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/cli.py", line 15, in <module>
    logging.info("Identify: %s", hs.identify())
  File "/home/hendrix/home/pyHS100/pyHS100/pyHS100.py", line 327, in identify
    return self.alias, self.model, self.features
  File "/home/hendrix/home/pyHS100/pyHS100/pyHS100.py", line 365, in alias
    return self.sys_info['alias']
  File "/home/hendrix/home/pyHS100/pyHS100/pyHS100.py", line 120, in sys_info
    self._fetch_sysinfo()
  File "/home/hendrix/home/pyHS100/pyHS100/pyHS100.py", line 86, in _fetch_sysinfo
    self._sys_info = self.get_sysinfo()
  File "/home/hendrix/home/pyHS100/pyHS100/pyHS100.py", line 176, in get_sysinfo
    return self._query_helper("system", "get_sysinfo")
  File "/home/hendrix/home/pyHS100/pyHS100/pyHS100.py", line 106, in _query_helper
    raise SmartPlugException(ex) from ex
pyHS100.pyHS100.SmartPlugException: timed out
```

2016-12-17 14:40 UTC, rytilahti requested changes
Looks good, but raise .. from should use raise_from to allow python 2.7 compatibility.

2016-12-17 14:40 UTC, rytilahti commented on pyHS100/pyHS100.py
> +            raise SmartPlugException(ex) from ex
I think we need to use ```raise_from``` in order to keep py27 compatibility.
See http://python-future.org/compatible_idioms.html#raising-exceptions

2017-01-05 04:49 UTC, rytilahti commented
@trainman419 mind fixing the "from ex"/raise_from issue?
@GadgetReactor can we get this merged?

2017-01-06 05:35 UTC, trainman419 commented on pyHS100/pyHS100.py
> +            raise SmartPlugException(ex) from ex
I've tried adding `from future.utils import raise_from` on my local copy, but now I get import errors about future.utils. I think I need to add it as a dependency, but I'm not sure how to do that and maintain python2/3 compatibility.

2017-01-06 07:15 UTC, trainman419 commented
Can someone with an HS100 or HS110 that speaks TCP test this?

On my HS105 it's causing timeouts even when my device sometimes sends a response.

2017-01-07 22:42 UTC, merged