Adds energy monitoring functionality available in the HS110 plugs
GadgetReactor/pyHS100 pull request #2
Opened 2016-10-13 15:35 UTC by kirichkov

Besides retrieving data I've also refactored the code for setting state to use the turn_on() and turn_off() methods.

2016-10-18 00:12 UTC, mweinelt commented on pyHS100/pyHS100.py
> +          self.turn_on()
underindented, this project seems to use 4 spaces, please don't introduce mixed indentation :)

2016-10-18 00:13 UTC, mweinelt commented on pyHS100/pyHS100.py
> +          self.turn_off()
underindented

2016-10-18 01:23 UTC, GadgetReactor commented
Apologies, was overseas. Thanks for the added changes! Will review and merge it in a couple of days.

2016-10-18 06:00 UTC, kirichkov commented
Can you please test the code against HS100, because I have only the HS110 and I can't reliably test whether the energy monitoring functions reliably work with switches that don't support the energy monitoring.

2016-10-19 01:55 UTC, GadgetReactor commented on pyHS100/pyHS100.py
> +
For consistency, remove blankline

2016-10-19 01:56 UTC, GadgetReactor commented on pyHS100/pyHS100.py
> +
Remove blankline, and also to check if smartplug supports function
<code>
        if self.model == 100:
            return False
</code>

2016-10-19 02:02 UTC, GadgetReactor requested changes
Sorry, not too familiar with the Github commenting / review process, but the new code works well. 
Suggest to implement a function check to the current_consumption.

Lastly, the HS100_status is now redundant. I will remove it subsequently, or do you want to do this in this pull request? A modification to def_state(self) is required though - 
        sys_info = self.get_info()
        response = sys_info["system"]["get_sysinfo"]["relay_state"]

2016-10-19 08:05 UTC, kirichkov commented
Thanks for reviewing and spotting the issue with `current_consumption()`

I've refactored the state property method and completely removed the hs100_status() method as you suggested.

2016-10-19 08:09 UTC, GadgetReactor approved these changes
Looks great! Thanks.

2016-10-19 08:10 UTC, merged