Ignore error when closing read side of socket after closing write side
GadgetReactor/pyHS100 pull request #23
Opened 2016-12-31 18:00 UTC by harmingcola

On Mac OS X, shutdown(SHUT_RD) fails if the write side on the other side has been closed.

2017-01-05 04:53 UTC, rytilahti requested changes
Please avoid using "catch all" except: https://docs.python.org/2.7/howto/doanddont.html#except

Also please add a short comment why exceptions are pass'd.

2017-01-07 22:06 UTC, dims commented
I've tested this change. works for me!

2017-01-11 15:52 UTC, mweinelt commented
Should probably move `sock.close()` into finally and downgrade to `sock.shutdown(socket.SHUT_RD)`.

2017-03-01 01:29 UTC, rytilahti commented
@GadgetReactor any news on this?

2017-03-17 13:37 UTC, rytilahti approved these changes

2017-03-17 14:08 UTC, mweinelt commented
@harmingcola Can you please rebase this PR against master? We'll get it merged quickly then.

2017-03-19 13:58 UTC, mweinelt commented
I'm not sure we still need this after the latest protocol changes after all.

2017-03-19 14:25 UTC, rytilahti commented
Do you have some specific reason for that? From what I see the original problem is caused by calling shutdown() on a closed socket on OSX which are not at least directly affected by those protocol changes.

2017-03-19 16:16 UTC, closed without merging

2017-03-19 16:17 UTC, mweinelt commented
Obsoleted in #41