Try to resolve hostname before opening a socket
GadgetReactor/pyHS100 pull request #32
Opened 2017-01-14 23:27 UTC by craigcabrey

If `ip_address` is already an IP address, `gethostbyname()` will simply return it unmodified.

2017-01-14 23:41 UTC, rytilahti approved these changes
Looks fine to me.

2017-01-15 16:24 UTC, kirichkov approved these changes
👍

2017-01-15 16:44 UTC, mweinelt commented
If we start accepting hostnames, lets rename the function parameter to `host`.

Besides that, https://github.com/GadgetReactor/pyHS100/pull/32/files#diff-3475cfc85c1bad6f0bd35e52795d77e8R79 is intended to validate ip addresses, if we pipe them through `gethostbyname`, what purpose does it still serve?

2017-01-15 16:45 UTC, mweinelt requested changes
Rename the functions `ip_address` parameter to host

2017-01-15 16:53 UTC, kirichkov commented
https://github.com/GadgetReactor/pyHS100/pull/32/files#diff-3475cfc85c1bad6f0bd35e52795d77e8R79 should indeed be removed.

2017-01-15 17:16 UTC, craigcabrey commented
Ah, I didn't realize that the socket wasn't actually for communication, just validation. Good catch :+1:. I'll play around with `getaddrinfo` to see how it behaves in IPv4-only, IPv6-only, and mixed environments.

2017-03-17 13:42 UTC, rytilahti commented
I'm wondering whether this is really necessary?

2017-03-17 14:10 UTC, mweinelt commented
It's no harm doing dns lookups, and in a more organized automation setup working with hostnames might be desirable. So I'm in favor for this functionality.

2017-03-19 15:01 UTC, rytilahti commented
Fair enough indeed, it needs to be ported to use getaddrinfo before getting merged.

2017-03-19 16:19 UTC, mweinelt commented
@craigcabrey Are you interested in resolving the outstanding issues?

2017-05-17 17:38 UTC, kirichkov commented
I believe this has gone stale.

@craigcabrey are you interested in finishing this up,or should I close the pull request?

2017-08-03 08:40 UTC, kirichkov commented
This has gone stale. Closing it. Please reopen when ready.

2017-08-03 08:40 UTC, closed without merging